# Generated by Django 5.1.6 on 2025-03-03 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
