# Generated by Django 5.1.5 on 2025-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_portfolio_portfolioitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioitem",
            name="purchase_price",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="quantity",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
