# Generated by Django 5.1.6 on 2025-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_portfolioitem_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=8, default=10000.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=7, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='quantity',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
    ]
