# Generated by Django 5.1.5 on 2025-02-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_lesson_created_at_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, default='tradeoasis.jpeg', null=True, upload_to=''),
        ),
    ]
