# Generated by Django 5.1.5 on 2025-02-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lesson_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, default='tradeoasis.jpeg', upload_to=''),
        ),
    ]
