# Generated by Django 5.1.5 on 2025-02-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_lesson_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(default='tradeoasis.jpg', upload_to=''),
        ),
    ]
