# Generated by Django 5.1.6 on 2025-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_lesson_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(default='static/logo.png', upload_to=''),
        ),
    ]
