# Generated by Django 5.1.6 on 2025-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0009_alter_lesson_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="thumbnail",
            field=models.ImageField(default="logo.png", upload_to=""),
        ),
    ]
